In [7]:
import pandas as pd

In [9]:
sbux = pd.read_csv("https://raw.githubusercontent.com/professorfoy/BUS-303-Python-for-Business/refs/heads/main/BUS303_Signature_Term_Project_Starbucks_Beverage_Menu.csv")
sbux

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,zero,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,White Hot Chocolate,Venti®,Whole,Whip,591.0,640.0,28.0,18.0,0.5,75.0,330.0,78.0,0.0,78,19.0,30.0,2.0,60.0,2.0,0.0
1201,White Hot Chocolate,Venti®,Soy,No Whip,591.0,470.0,14.0,7.0,0.0,5.0,290.0,69.0,2.0,65,16.0,15.0,2.0,60.0,20.0,0.0
1202,White Hot Chocolate,Venti®,Soy,Whip,591.0,540.0,21.0,11.0,0.2,30.0,300.0,71.0,2.0,67,17.0,25.0,2.0,60.0,20.0,0.0
1203,White Hot Chocolate,Venti®,Coconut,No Whip,591.0,450.0,17.0,15.0,0.0,5.0,310.0,71.0,0.0,69,6.0,0.0,2.0,15.0,0.0,0.0
1204,White Hot Chocolate,Venti®,Coconut,Whip,591.0,520.0,24.0,20.0,0.2,30.0,320.0,73.0,0.0,71,6.0,8.0,2.0,15.0,0.0,0.0

In [11]:
sbux.isnull().sum()

Product_Name           1
Size                   1
Milk                   1
Whip                   1
Serving_Size_ml        1
Calories               1
Total_Fat_g            1
Saturated_Fat_g        2
Trans_Fat_g            1
Cholesterol_mg         1
Sodium_mg              1
Carbohydrates_g        1
Dietary_Fiber_g        1
Sugar_g                1
Protein_g              1
Vitamin_A_%DV          1
Vitamin_C_%DV          1
Calcium_%DV            1
Iron_%DV               1
Caffiene_milligrams    1
dtype: int64

In [12]:
sbux.head(15)

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,zero,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
5,Brewed Coffee - Decaf Pike Place® Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,15.0
6,Brewed Coffee - Decaf Pike Place® Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,0.5,0.0,0.0,0.0,0.0,20.0
7,Brewed Coffee - Decaf Pike Place® Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,25.0
8,Brewed Coffee - Decaf Pike Place® Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,30.0
9,Brewed Coffee Traveler - Decaf Pike Place® Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,15.0
10,Brewed Coffee - Medium Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,155.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Brewed Coffee - Medium Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,0.5,0.0,0.0,0.0,0.0,235.0
13,Brewed Coffee - Medium Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,310.0
14,Brewed Coffee - Medium Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,410.0

In [39]:
sbux1 = sbux.dropna(how='all').copy()

In [40]:
sbux.isnull().sum()

Product_Name           1
Size                   1
Milk                   1
Whip                   1
Serving_Size_ml        1
Calories               1
Total_Fat_g            1
Saturated_Fat_g        2
Trans_Fat_g            1
Cholesterol_mg         1
Sodium_mg              1
Carbohydrates_g        1
Dietary_Fiber_g        1
Sugar_g                1
Protein_g              1
Vitamin_A_%DV          1
Vitamin_C_%DV          1
Calcium_%DV            1
Iron_%DV               1
Caffiene_milligrams    1
dtype: int64

In [41]:
sbux1.info()

<class 'pandas.DataFrame'>
Index: 1204 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Name         1204 non-null   str
 1   Size                 1204 non-null   str
 2   Milk                 1204 non-null   str
 3   Whip                 1204 non-null   str
 4   Serving_Size_ml      1204 non-null   float64
 5   Calories             1204 non-null   float64
 6   Total_Fat_g          1204 non-null   float64
 7   Saturated_Fat_g      1203 non-null   float64
 8   Trans_Fat_g          1204 non-null   float64
 9   Cholesterol_mg       1204 non-null   float64
 10  Sodium_mg            1204 non-null   float64
 11  Carbohydrates_g      1204 non-null   float64
 12  Dietary_Fiber_g      1204 non-null   float64
 13  Sugar_g              1204 non-null   str
 14  Protein_g            1204 non-null   float64
 15  Vitamin_A_%DV        1204 non-null   float64
 16  Vitamin_C_%DV        1204 non-null   float64
 17  Calcium_%DV          1204 non-null   float64
 18  Iron_%DV             1204 non-null   float64
 19  Caffiene_milligrams  1204 non-null   float64
dtypes: float64(15), str(5)
memory usage: 251.8 KB

In [45]:
sbux1.iloc[1,13] = "0"
sbux1

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,White Hot Chocolate,Venti®,Whole,Whip,591.0,640.0,28.0,18.0,0.5,75.0,330.0,78.0,0.0,78,19.0,30.0,2.0,60.0,2.0,0.0
1201,White Hot Chocolate,Venti®,Soy,No Whip,591.0,470.0,14.0,7.0,0.0,5.0,290.0,69.0,2.0,65,16.0,15.0,2.0,60.0,20.0,0.0
1202,White Hot Chocolate,Venti®,Soy,Whip,591.0,540.0,21.0,11.0,0.2,30.0,300.0,71.0,2.0,67,17.0,25.0,2.0,60.0,20.0,0.0
1203,White Hot Chocolate,Venti®,Coconut,No Whip,591.0,450.0,17.0,15.0,0.0,5.0,310.0,71.0,0.0,69,6.0,0.0,2.0,15.0,0.0,0.0
1204,White Hot Chocolate,Venti®,Coconut,Whip,591.0,520.0,24.0,20.0,0.2,30.0,320.0,73.0,0.0,71,6.0,8.0,2.0,15.0,0.0,0.0

In [46]:
sbux1["Sugar_g"] = sbux1["Sugar_g"].astype(float)

In [48]:
sbux1.Sugar_g.dtypes

dtype('float64')

In [49]:
sbux1.info()

<class 'pandas.DataFrame'>
Index: 1204 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Name         1204 non-null   str
 1   Size                 1204 non-null   str
 2   Milk                 1204 non-null   str
 3   Whip                 1204 non-null   str
 4   Serving_Size_ml      1204 non-null   float64
 5   Calories             1204 non-null   float64
 6   Total_Fat_g          1204 non-null   float64
 7   Saturated_Fat_g      1203 non-null   float64
 8   Trans_Fat_g          1204 non-null   float64
 9   Cholesterol_mg       1204 non-null   float64
 10  Sodium_mg            1204 non-null   float64
 11  Carbohydrates_g      1204 non-null   float64
 12  Dietary_Fiber_g      1204 non-null   float64
 13  Sugar_g              1204 non-null   float64
 14  Protein_g            1204 non-null   float64
 15  Vitamin_A_%DV        1204 non-null   float64
 16  Vitamin_C_%DV        1204 non-null   float64
 17  Calcium_%DV          1204 non-null   float64
 18  Iron_%DV             1204 non-null   float64
 19  Caffiene_milligrams  1204 non-null   float64
dtypes: float64(16), str(4)
memory usage: 249.4 KB

In [50]:
sbux2 = sbux1.dropna()

In [51]:
sbux2.info()

<class 'pandas.DataFrame'>
Index: 1203 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Name         1203 non-null   str
 1   Size                 1203 non-null   str
 2   Milk                 1203 non-null   str
 3   Whip                 1203 non-null   str
 4   Serving_Size_ml      1203 non-null   float64
 5   Calories             1203 non-null   float64
 6   Total_Fat_g          1203 non-null   float64
 7   Saturated_Fat_g      1203 non-null   float64
 8   Trans_Fat_g          1203 non-null   float64
 9   Cholesterol_mg       1203 non-null   float64
 10  Sodium_mg            1203 non-null   float64
 11  Carbohydrates_g      1203 non-null   float64
 12  Dietary_Fiber_g      1203 non-null   float64
 13  Sugar_g              1203 non-null   float64
 14  Protein_g            1203 non-null   float64
 15  Vitamin_A_%DV        1203 non-null   float64
 16  Vitamin_C_%DV        1203 non-null   float64
 17  Calcium_%DV          1203 non-null   float64
 18  Iron_%DV             1203 non-null   float64
 19  Caffiene_milligrams  1203 non-null   float64
dtypes: float64(16), str(4)
memory usage: 249.2 KB

In [52]:
sbux3 = sbux2.rename(columns = {'Caffiene_milligrams':'Caffiene_mg'})

In [53]:
sbux3.info()

<class 'pandas.DataFrame'>
Index: 1203 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Product_Name     1203 non-null   str
 1   Size             1203 non-null   str
 2   Milk             1203 non-null   str
 3   Whip             1203 non-null   str
 4   Serving_Size_ml  1203 non-null   float64
 5   Calories         1203 non-null   float64
 6   Total_Fat_g      1203 non-null   float64
 7   Saturated_Fat_g  1203 non-null   float64
 8   Trans_Fat_g      1203 non-null   float64
 9   Cholesterol_mg   1203 non-null   float64
 10  Sodium_mg        1203 non-null   float64
 11  Carbohydrates_g  1203 non-null   float64
 12  Dietary_Fiber_g  1203 non-null   float64
 13  Sugar_g          1203 non-null   float64
 14  Protein_g        1203 non-null   float64
 15  Vitamin_A_%DV    1203 non-null   float64
 16  Vitamin_C_%DV    1203 non-null   float64
 17  Calcium_%DV      1203 non-null   float64
 18  Iron_%DV         1203 non-null   float64
 19  Caffiene_mg      1203 non-null   float64
dtypes: float64(16), str(4)
memory usage: 249.2 KB

In [54]:
sbux3.to_csv('sbux4.csv', index=False)

In [55]:
sbux4 = pd.read_csv('sbux4.csv')

In [56]:
sbux4.head()

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_mg
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,130.0