In [7]:
import pandas as pd

In [9]:
sbux = pd.read_csv("https://raw.githubusercontent.com/professorfoy/BUS-303-Python-for-Business/refs/heads/main/BUS303_Signature_Term_Project_Starbucks_Beverage_Menu.csv")
sbux

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,zero,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,White Hot Chocolate,Venti®,Whole,Whip,591.0,640.0,28.0,18.0,0.5,75.0,330.0,78.0,0.0,78,19.0,30.0,2.0,60.0,2.0,0.0
1201,White Hot Chocolate,Venti®,Soy,No Whip,591.0,470.0,14.0,7.0,0.0,5.0,290.0,69.0,2.0,65,16.0,15.0,2.0,60.0,20.0,0.0
1202,White Hot Chocolate,Venti®,Soy,Whip,591.0,540.0,21.0,11.0,0.2,30.0,300.0,71.0,2.0,67,17.0,25.0,2.0,60.0,20.0,0.0
1203,White Hot Chocolate,Venti®,Coconut,No Whip,591.0,450.0,17.0,15.0,0.0,5.0,310.0,71.0,0.0,69,6.0,0.0,2.0,15.0,0.0,0.0
1204,White Hot Chocolate,Venti®,Coconut,Whip,591.0,520.0,24.0,20.0,0.2,30.0,320.0,73.0,0.0,71,6.0,8.0,2.0,15.0,0.0,0.0

In [11]:
sbux.isnull().sum()

Product_Name           1
Size                   1
Milk                   1
Whip                   1
Serving_Size_ml        1
Calories               1
Total_Fat_g            1
Saturated_Fat_g        2
Trans_Fat_g            1
Cholesterol_mg         1
Sodium_mg              1
Carbohydrates_g        1
Dietary_Fiber_g        1
Sugar_g                1
Protein_g              1
Vitamin_A_%DV          1
Vitamin_C_%DV          1
Calcium_%DV            1
Iron_%DV               1
Caffiene_milligrams    1
dtype: int64

In [12]:
sbux.head(15)

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,zero,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
5,Brewed Coffee - Decaf Pike Place® Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,15.0
6,Brewed Coffee - Decaf Pike Place® Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,0.5,0.0,0.0,0.0,0.0,20.0
7,Brewed Coffee - Decaf Pike Place® Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,25.0
8,Brewed Coffee - Decaf Pike Place® Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,30.0
9,Brewed Coffee Traveler - Decaf Pike Place® Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,15.0
10,Brewed Coffee - Medium Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,155.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Brewed Coffee - Medium Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,0.5,0.0,0.0,0.0,0.0,235.0
13,Brewed Coffee - Medium Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,310.0
14,Brewed Coffee - Medium Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,410.0

In [39]:
sbux1 = sbux.dropna(how='all').copy()

In [40]:
sbux1
    .isnull().sum()

Product_Name           1
Size                   1
Milk                   1
Whip                   1
Serving_Size_ml        1
Calories               1
Total_Fat_g            1
Saturated_Fat_g        2
Trans_Fat_g            1
Cholesterol_mg         1
Sodium_mg              1
Carbohydrates_g        1
Dietary_Fiber_g        1
Sugar_g                1
Protein_g              1
Vitamin_A_%DV          1
Vitamin_C_%DV          1
Calcium_%DV            1
Iron_%DV               1
Caffiene_milligrams    1
dtype: int64

In [41]:
sbux1.info()

<class 'pandas.DataFrame'>
Index: 1204 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Name         1204 non-null   str
 1   Size                 1204 non-null   str
 2   Milk                 1204 non-null   str
 3   Whip                 1204 non-null   str
 4   Serving_Size_ml      1204 non-null   float64
 5   Calories             1204 non-null   float64
 6   Total_Fat_g          1204 non-null   float64
 7   Saturated_Fat_g      1203 non-null   float64
 8   Trans_Fat_g          1204 non-null   float64
 9   Cholesterol_mg       1204 non-null   float64
 10  Sodium_mg            1204 non-null   float64
 11  Carbohydrates_g      1204 non-null   float64
 12  Dietary_Fiber_g      1204 non-null   float64
 13  Sugar_g              1204 non-null   str
 14  Protein_g            1204 non-null   float64
 15  Vitamin_A_%DV        1204 non-null   float64
 16  Vitamin_C_%DV        1204 non-null   float64
 17  Calcium_%DV          1204 non-null   float64
 18  Iron_%DV             1204 non-null   float64
 19  Caffiene_milligrams  1204 non-null   float64
dtypes: float64(15), str(5)
memory usage: 251.8 KB

In [45]:
sbux1.iloc[1,13] = "0"
sbux1

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,White Hot Chocolate,Venti®,Whole,Whip,591.0,640.0,28.0,18.0,0.5,75.0,330.0,78.0,0.0,78,19.0,30.0,2.0,60.0,2.0,0.0
1201,White Hot Chocolate,Venti®,Soy,No Whip,591.0,470.0,14.0,7.0,0.0,5.0,290.0,69.0,2.0,65,16.0,15.0,2.0,60.0,20.0,0.0
1202,White Hot Chocolate,Venti®,Soy,Whip,591.0,540.0,21.0,11.0,0.2,30.0,300.0,71.0,2.0,67,17.0,25.0,2.0,60.0,20.0,0.0
1203,White Hot Chocolate,Venti®,Coconut,No Whip,591.0,450.0,17.0,15.0,0.0,5.0,310.0,71.0,0.0,69,6.0,0.0,2.0,15.0,0.0,0.0
1204,White Hot Chocolate,Venti®,Coconut,Whip,591.0,520.0,24.0,20.0,0.2,30.0,320.0,73.0,0.0,71,6.0,8.0,2.0,15.0,0.0,0.0

In [46]:
sbux1["Sugar_g"] = sbux1["Sugar_g"].astype(float)

In [48]:
sbux1.Sugar_g.dtypes

dtype('float64')

In [49]:
sbux1.info()

<class 'pandas.DataFrame'>
Index: 1204 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Name         1204 non-null   str
 1   Size                 1204 non-null   str
 2   Milk                 1204 non-null   str
 3   Whip                 1204 non-null   str
 4   Serving_Size_ml      1204 non-null   float64
 5   Calories             1204 non-null   float64
 6   Total_Fat_g          1204 non-null   float64
 7   Saturated_Fat_g      1203 non-null   float64
 8   Trans_Fat_g          1204 non-null   float64
 9   Cholesterol_mg       1204 non-null   float64
 10  Sodium_mg            1204 non-null   float64
 11  Carbohydrates_g      1204 non-null   float64
 12  Dietary_Fiber_g      1204 non-null   float64
 13  Sugar_g              1204 non-null   float64
 14  Protein_g            1204 non-null   float64
 15  Vitamin_A_%DV        1204 non-null   float64
 16  Vitamin_C_%DV        1204 non-null   float64
 17  Calcium_%DV          1204 non-null   float64
 18  Iron_%DV             1204 non-null   float64
 19  Caffiene_milligrams  1204 non-null   float64
dtypes: float64(16), str(4)
memory usage: 249.4 KB

In [50]:
sbux2 = sbux1.dropna()

In [51]:
sbux2.info()

<class 'pandas.DataFrame'>
Index: 1203 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Name         1203 non-null   str
 1   Size                 1203 non-null   str
 2   Milk                 1203 non-null   str
 3   Whip                 1203 non-null   str
 4   Serving_Size_ml      1203 non-null   float64
 5   Calories             1203 non-null   float64
 6   Total_Fat_g          1203 non-null   float64
 7   Saturated_Fat_g      1203 non-null   float64
 8   Trans_Fat_g          1203 non-null   float64
 9   Cholesterol_mg       1203 non-null   float64
 10  Sodium_mg            1203 non-null   float64
 11  Carbohydrates_g      1203 non-null   float64
 12  Dietary_Fiber_g      1203 non-null   float64
 13  Sugar_g              1203 non-null   float64
 14  Protein_g            1203 non-null   float64
 15  Vitamin_A_%DV        1203 non-null   float64
 16  Vitamin_C_%DV        1203 non-null   float64
 17  Calcium_%DV          1203 non-null   float64
 18  Iron_%DV             1203 non-null   float64
 19  Caffiene_milligrams  1203 non-null   float64
dtypes: float64(16), str(4)
memory usage: 249.2 KB

In [52]:
sbux3 = sbux2.rename(columns = {'Caffiene_milligrams':'Caffiene_mg'})

In [53]:
sbux3.info()

<class 'pandas.DataFrame'>
Index: 1203 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Product_Name     1203 non-null   str
 1   Size             1203 non-null   str
 2   Milk             1203 non-null   str
 3   Whip             1203 non-null   str
 4   Serving_Size_ml  1203 non-null   float64
 5   Calories         1203 non-null   float64
 6   Total_Fat_g      1203 non-null   float64
 7   Saturated_Fat_g  1203 non-null   float64
 8   Trans_Fat_g      1203 non-null   float64
 9   Cholesterol_mg   1203 non-null   float64
 10  Sodium_mg        1203 non-null   float64
 11  Carbohydrates_g  1203 non-null   float64
 12  Dietary_Fiber_g  1203 non-null   float64
 13  Sugar_g          1203 non-null   float64
 14  Protein_g        1203 non-null   float64
 15  Vitamin_A_%DV    1203 non-null   float64
 16  Vitamin_C_%DV    1203 non-null   float64
 17  Calcium_%DV      1203 non-null   float64
 18  Iron_%DV         1203 non-null   float64
 19  Caffiene_mg      1203 non-null   float64
dtypes: float64(16), str(4)
memory usage: 249.2 KB

In [54]:
sbux3.to_csv('sbux4.csv', index=False)

In [55]:
sbux4 = pd.read_csv('sbux4.csv')

In [56]:
sbux4.head()

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_mg
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,130.0

In [3]:
import pandas as pd

In [11]:
dnkn = pd.read_csv("https://raw.githubusercontent.com/professorfoy/BUS-303-Python-for-Business/refs/heads/main/BUS_303_Dunkin_Donuts_Nutritional_Menu_Kaggle_2023.csv")
dnkn

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
0,Cold Brew Coffee,"Cold Brew Coffee, Large",5,0,0,0,0,20,0,0,0,1,4
1,Cold Brew Coffee,"Cold Brew Coffee, Medium",5,0,0,0,0,15,0,0,0,0,5
2,Cold Brew Coffee,"Cold Brew Coffee, Small",5,0,0,0,0,10,0,0,0,0,5
3,Cold Brew Coffee,"Cold Brew Coffee with Cream, Large",120,12,6,0,35,65,2,0,2,2,126
4,Cold Brew Coffee,"Cold Brew Coffee with Cream, Medium",90,9,4.5,0,25,45,1,0,1,2,93.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,Soft Serve,OREO Mix-In,510,21,11,0.5,55,350,70,2,55,14,562
776,Soft Serve,Soft Serve Cone,260,9,6,0,35,160,35,1,27,9,284
777,Soft Serve,Strawberry Coolatta Float,420,12,8,0,50,210,68,1,64,11,481
778,Hash Browns,Hash Browns,130,6,1,0,0,420,12,2,0,5,126
779,Dunkin’ Bowls,Egg White Bowl,250,11,4,0,15,490,20,0,3,14,243

In [12]:
dnkn.info()

<class 'pandas.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Category             780 non-null    str
 1   Item                 780 non-null    str
 2   Calories             780 non-null    str
 3   Total Fat (g)        780 non-null    str
 4   Saturated Fat (g)    780 non-null    str
 5   Trans Fat (g)        780 non-null    str
 6   Cholesterol (mg)     780 non-null    str
 7   Sodium (mg)          780 non-null    str
 8   Carbs (g)            780 non-null    str
 9   Fiber (g)            780 non-null    str
 10  Sugars (g)           780 non-null    str
 11  Protein (g)          780 non-null    str
 12  Weight Watcher Pnts  780 non-null    str
dtypes: str(13)
memory usage: 132.8 KB

In [13]:
dnkn.isnull().sum()

Category               0
Item                   0
Calories               0
Total Fat (g)          0
Saturated Fat (g)      0
Trans Fat (g)          0
Cholesterol (mg)       0
Sodium (mg)            0
Carbs (g)              0
Fiber (g)              0
Sugars (g)             0
Protein (g)            0
Weight Watcher Pnts    0
dtype: int64

In [14]:
dnkn.duplicated().sum()

np.int64(1)

In [15]:
dnkn[dnkn.duplicated()]

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
760,Sandwiches,Ham and Cheese Rollups,280,13,6,0,40,1050,27,1,2,13,275

In [16]:
dnkn.nunique()

Category                23
Item                   779
Calories                87
Total Fat (g)           50
Saturated Fat (g)       29
Trans Fat (g)            5
Cholesterol (mg)        37
Sodium (mg)            112
Carbs (g)              120
Fiber (g)                9
Sugars (g)             122
Protein (g)             32
Weight Watcher Pnts    362
dtype: int64

In [17]:
dnkn['Category'].value_counts()

Category
Hot Coffee            88
Donuts                87
Hot Latte             63
Iced Coffee           63
Iced Latte            63
Sandwiches            55
Frozen Coffee         49
Hot Macchiato         45
Hot Cappuccino        43
Iced Cappuccino       42
Iced Macchiato        42
Iced Tea              33
Hot Chocolate         28
Muffins               18
Kolache               16
Cold Brew Coffee      11
Coolatta               9
Dunkin’ Refreshers     9
Soft Serve             8
Hot Americano          3
Iced Americano         3
Hash Browns            1
Dunkin’ Bowls          1
Name: count, dtype: int64

In [18]:
dnkn.describe(include='all')

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
count,780,780,780,780,780,780,780,780,780,780,780,780,780
unique,23,779,87,50,29,5,37,112,120,9,122,32,362
top,Hot Coffee,Ham and Cheese Rollups,170,0,0,0,0,180,35,0,0,4,5
freq,88,2,38,242,269,755,222,24,30,508,33,94,13

In [19]:
dnkn['Total Fat (g)'].unique()

<ArrowStringArray>
[  '0',  '12',   '9',   '6', '4.5',   '3',  '10',  '11',  '28',  '30',  '22',
  '21',  '23',  '14',  '15',  '20',  '19',  '16',  '18',  '25',  '31',  '27',
  '17',  '37',  '40',   '5',   '8',  '35',  '26',  '13',   '7',   ' ',   '4',
   '1', '0.5', '1.5', '2.5',   '2', '3.5',  '42',  '33',  '24',  '36',  '54',
  '29',  '32',  '34',  '52',  '41',  '43']
Length: 50, dtype: str

In [20]:
dnkn['Saturated Fat (g)'].unique()

<ArrowStringArray>
[  '0',   '6', '4.5',   '3', '3.5', '2.5', '1.5',   '4',  '12',  '14',   '9',
  '10',  '11',   '7',   '5',   '8',  '13',  '18',  '22',  '17',  '15',   ' ',
 '0.5',  '19',  '21',   '1',   '2',  '20',  '16']
Length: 29, dtype: str

In [21]:
dnkn['Trans Fat (g)'].unique()

<ArrowStringArray>
['0', '1.5', '1', '0.5', ' ']
Length: 5, dtype: str

In [22]:
dnkn['Cholesterol (mg)'].unique()

<ArrowStringArray>
[  '0',  '35',  '25',  '20',  '15',  '10',  '50',  '30',  '40', '130', '100',
  '70', '105',  '80',  '55',  '<5',   ' ', '125',  '45',  '60', '185', '340',
 '180',  '95',  '65', '190', '360', '195', '265', '175', '220', '120', '200',
 '240', '205', '110', '115']
Length: 37, dtype: str

In [23]:
dnkn['Sodium (mg)'].unique()

<ArrowStringArray>
[  '20',   '15',   '10',   '65',   '45',   '30',    '5',   '60',  '320',
  '240',
 ...
  '710',  '550',  '850',  '490',  '760',  '970',  '580', '1160',  '700',
  '680']
Length: 112, dtype: str

In [24]:
dnkn['Fiber (g)'].unique()

<ArrowStringArray>
['0', '1', '2', '3', '4', ' ', '6', '5', '8']
Length: 9, dtype: str

In [25]:
dnkn['Protein (g)'].unique()

<ArrowStringArray>
[ '1',  '0',  '2', '10',  '7',  '5',  '4',  '6',  '3',  '8', '11',  '9',  ' ',
 '12', '16', '15', '14', '13', '27', '24', '37', '17', '19', '26', '21', '23',
 '18', '28', '33', '22', '25', '20']
Length: 32, dtype: str

In [27]:
dnkn['Carbs (g)'].unique()

<ArrowStringArray>
[  '0',   '2',   '1',  '37',  '27',  '18', '112',  '84',  '56', '172',
 ...
  '14',  '69',  '22',  '75',  '77',  '29',  '74',  '68',   '8',  '92']
Length: 120, dtype: str

In [28]:
dnkn['Sugars (g)'].unique()

<ArrowStringArray>
[  '0',   '2',   '1',  '36',  '27',  '18', '110',  '83',  '55', '167',
 ...
  '59',  '48',  '74',  '52',  '68',  '67',  '78',   '8',  '44',  '85']
Length: 122, dtype: str

In [30]:
dnkn1 = dnkn.copy()
dnkn1

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
0,Cold Brew Coffee,"Cold Brew Coffee, Large",5,0,0,0,0,20,0,0,0,1,4
1,Cold Brew Coffee,"Cold Brew Coffee, Medium",5,0,0,0,0,15,0,0,0,0,5
2,Cold Brew Coffee,"Cold Brew Coffee, Small",5,0,0,0,0,10,0,0,0,0,5
3,Cold Brew Coffee,"Cold Brew Coffee with Cream, Large",120,12,6,0,35,65,2,0,2,2,126
4,Cold Brew Coffee,"Cold Brew Coffee with Cream, Medium",90,9,4.5,0,25,45,1,0,1,2,93.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,Soft Serve,OREO Mix-In,510,21,11,0.5,55,350,70,2,55,14,562
776,Soft Serve,Soft Serve Cone,260,9,6,0,35,160,35,1,27,9,284
777,Soft Serve,Strawberry Coolatta Float,420,12,8,0,50,210,68,1,64,11,481
778,Hash Browns,Hash Browns,130,6,1,0,0,420,12,2,0,5,126
779,Dunkin’ Bowls,Egg White Bowl,250,11,4,0,15,490,20,0,3,14,243

In [32]:
food_items = ['Donuts', 'Sandwiches', 'Muffins', 'Hash Browns', 'Dunkin Bowls', 'Kolache']
dnkn2=dnkn1[~dnkn1['Category'].isin(food_items)].copy()

In [33]:
dnkn2.duplicated().sum()

np.int64(0)

In [49]:
dnkn2['Cholesterol (mg)'] = (
    dnkn2['Cholesterol (mg)']
        .replace('<5', '5')
)

In [48]:
for col in dnkn2.select_dtypes(include=['object', 'str']).columns:
    dnkn2[col] = (
        dnkn2[col]
            .str.replace('\xa0', '', regex=False)
            .str.strip()
    )

In [53]:
for col in dnkn2.select_dtypes(include=['object','str']).columns:
        print('\n', col)
        print(dnkn2[col].unique()[:50])

 Category
<ArrowStringArray>
[  'Cold Brew Coffee',           'Coolatta',      'Frozen Coffee',
      'Hot Americano',     'Hot Cappuccino',      'Hot Chocolate',
         'Hot Coffee',          'Hot Latte',      'Hot Macchiato',
     'Iced Americano',    'Iced Cappuccino',        'Iced Coffee',
         'Iced Latte',     'Iced Macchiato',           'Iced Tea',
 'Dunkin’ Refreshers',         'Soft Serve',      'Dunkin’ Bowls']
Length: 18, dtype: str

 Item
<ArrowStringArray>
[                                   'Cold Brew Coffee, Large',
                                   'Cold Brew Coffee, Medium',
                                    'Cold Brew Coffee, Small',
                         'Cold Brew Coffee with Cream, Large',
                        'Cold Brew Coffee with Cream, Medium',
                         'Cold Brew Coffee with Cream, Small',
               'Cold Brew Coffee with Cream and Sugar, Large',
              'Cold Brew Coffee with Cream and Sugar, Medium',
               'Cold Brew Coffee with Cream and Sugar, Small',
                             'Nitro Cold Brew Coffee, Medium',
                              'Nitro Cold Brew Coffee, Small',
                             'Blue Raspberry Coolatta, Large',
                            'Blue Raspberry Coolatta, Medium',
                             'Blue Raspberry Coolatta, Small',
                               'Vanilla Bean Coolatta, Large',
                              'Vanilla Bean Coolatta, Medium',
                               'Vanilla Bean Coolatta, Small',
                                  'Pineapple Coolatta, Large',
                                 'Pineapple Coolatta, Medium',
                                  'Pineapple Coolatta, Small',
              'Caramel Swirl Frozen Coffee with Cream, Large',
             'Caramel Swirl Frozen Coffee with Cream, Medium',
              'Caramel Swirl Frozen Coffee with Cream, Small',
          'Caramel Swirl Frozen Coffee with Skim Milk, Large',
         'Caramel Swirl Frozen Coffee with Skim Milk, Medium',
          'Caramel Swirl Frozen Coffee with Skim Milk, Small',
         'Caramel Swirl Frozen Coffee with Whole Milk, Large',
        'Caramel Swirl Frozen Coffee with Whole Milk, Medium',
         'Caramel Swirl Frozen Coffee with Whole Milk, Small',
       'French Vanilla Swirl Frozen Coffee with Cream, Large',
      'French Vanilla Swirl Frozen Coffee with Cream, Medium',
       'French Vanilla Swirl Frozen Coffee with Cream, Small',
   'French Vanilla Swirl Frozen Coffee with Skim Milk, Large',
  'French Vanilla Swirl Frozen Coffee with Skim Milk, Medium',
   'French Vanilla Swirl Frozen Coffee with Skim Milk, Small',
  'French Vanilla Swirl Frozen Coffee with Whole Milk, Large',
 'French Vanilla Swirl Frozen Coffee with Whole Milk, Medium',
  'French Vanilla Swirl Frozen Coffee with Whole Milk, Small',
                            'Frozen Coffee with Cream, Large',
                           'Frozen Coffee with Cream, Medium',
                            'Frozen Coffee with Cream, Small',
                        'Frozen Coffee with Skim Milk, Large',
                       'Frozen Coffee with Skim Milk, Medium',
                        'Frozen Coffee with Skim Milk, Small',
                       'Frozen Coffee with Whole Milk, Large',
                      'Frozen Coffee with Whole Milk, Medium',
                                   'Frozen Dunkaccino, Large',
                                  'Frozen Dunkaccino, Medium',
                                   'Frozen Dunkaccino, Small',
                   'Frozen Vanilla Chai/Vanilla Spice, Large']
Length: 50, dtype: str

 Calories
<ArrowStringArray>
[   '5',  '120',   '90',   '60',  '260',  '190',  '130',  '460',  '350',
  '230',  '790',  '590',  '390',  '340', '1120',  '860',  '610',  '830',
  '650',  '470',  '880',  '680',  '490', '1110',  '640',  '780',  '500',
  '370',  '250',  '550',  '410',  '930',  '710',  '510',  '400',     '',
 '1160',  '890',  '630',  '720',  '480',  '360',  '240',  '530',   '10',
   '70',   '45',  '170',  '110',  '160']
Length: 50, dtype: str

 Total Fat (g)
<ArrowStringArray>
[  '0',  '12',   '9',   '6', '4.5',   '3',  '40',  '31',  '22',   '5',  '11',
   '8',  '35',  '26',  '17',  '13',  '14',  '10',   '7',    '',   '4',   '1',
 '0.5',  '23',  '21',  '15',  '16', '1.5', '2.5',   '2',  '18', '3.5',  '20',
  '19',  '27']
Length: 35, dtype: str

 Saturated Fat (g)
<ArrowStringArray>
[  '0',   '6', '4.5',   '3', '3.5', '2.5', '1.5',  '22',  '17',  '12',   '7',
  '18',  '14',   '9',  '15',  '10',   '5',    '', '0.5',   '4',  '19',   '8',
  '21',  '13',  '11',   '1']
Length: 26, dtype: str

 Trans Fat (g)
<ArrowStringArray>
['0', '1.5', '1', '0.5', '']
Length: 5, dtype: str

 Cholesterol (mg)
<ArrowStringArray>
[  '0',  '35',  '25',  '20',  '15',  '10', '130', '100',  '70',  '40',  '30',
 '105',  '80',  '55',   '5',    '', '125',  '50',  '45',  '60']
Length: 20, dtype: str

 Sodium (mg)
<ArrowStringArray>
[ '20',  '15',  '10',  '65',  '45',  '30',   '5',  '60', '320', '240', '160',
 '290', '220', '180', '130', '280', '150', '230', '125', '200', '100', '115',
  '75', '350', '260', '120',    '', '480', '370', '250', '430', '330',  '95',
  '70',  '50',  '25',  '85',  '55', '135',  '90', '170', '140', '105', '110',
 '190', '210', '510', '470', '340', '570']
Length: 50, dtype: str

 Carbs (g)
<ArrowStringArray>
[  '0',   '2',   '1',  '37',  '27',  '18', '112',  '84',  '56', '172', '129',
  '86', '113',  '85', '180', '139',  '97', '184', '142',  '99', '141', '138',
 '183',  '57', '117',  '88',  '59', '177', '134',  '94', '160', '120',  '80',
    '', '191', '147', '103', '195', '150', '105', '111',  '83',  '55', '110',
  '13',  '10',   '7',  '48',  '36',  '24']
Length: 50, dtype: str

 Fiber (g)
<ArrowStringArray>
['0', '3', '2', '', '1', '4']
Length: 6, dtype: str

 Sugars (g)
<ArrowStringArray>
[  '0',   '2',   '1',  '36',  '27',  '18', '110',  '83',  '55', '167', '125',
 '107',  '80',  '53', '172', '132',  '92', '176', '135',  '94', '175', '134',
 '169', '130',  '91', '173', '133',  '93', '108',  '81',  '54', '112',  '84',
  '56', '111', '159', '119', '151', '113',  '75',    '', '181', '139',  '97',
 '185', '142',  '99',  '98', '109',  '82']
Length: 50, dtype: str

 Protein (g)
<ArrowStringArray>
[ '1',  '0',  '2', '10',  '7',  '5',  '8',  '6', '11',  '9',  '3',  '4',   '',
 '12', '16', '15', '14', '13', '19', '18']
Length: 20, dtype: str

 Weight Watcher Pnts
<ArrowStringArray>
[    '4',     '5',   '126',  '93.5',    '63',   '300', '219.5',   '150',
   '570',   '433',   '285', '950.5', '710.5', '469.5',   '567',   '420',
   '283',  '1304',  '1001',   '708', '998.5',   '779',   '561',  '1051',
   '812', '582.5',  '1291',   '999',   '707', '995.5',   '767',   '550',
  '1049',   '810', '580.5',   '899',   '680',   '450',   '604',   '448',
   '302', '657.5', '491.5',  '1094',   '833',   '597',   '942',   '703',
   '476',      '']
Length: 50, dtype: str

In [55]:
import numpy as np
dnkn2 = dnkn2.replace('',np.nan)

In [56]:
dnkn2.isnull().sum()

Category               0
Item                   0
Calories               3
Total Fat (g)          3
Saturated Fat (g)      3
Trans Fat (g)          3
Cholesterol (mg)       3
Sodium (mg)            3
Carbs (g)              3
Fiber (g)              3
Sugars (g)             3
Protein (g)            3
Weight Watcher Pnts    3
dtype: int64

In [57]:
dnkn3 = dnkn2.dropna().copy()

In [58]:
dnkn3.isnull().sum()

Category               0
Item                   0
Calories               0
Total Fat (g)          0
Saturated Fat (g)      0
Trans Fat (g)          0
Cholesterol (mg)       0
Sodium (mg)            0
Carbs (g)              0
Fiber (g)              0
Sugars (g)             0
Protein (g)            0
Weight Watcher Pnts    0
dtype: int64

In [62]:
numeric_columns = [
    'Calories',
    'Total Fat (g)',
    'Saturated Fat (g)',
    'Trans Fat (g)',
    'Cholesterol (mg)',
    'Sodium (mg)',
    'Carbs (g)',
    'Fiber (g)',
    'Sugars (g)',
    'Protein (g)',
    'Weight Watcher Pnts'
]
for col in numeric_columns:
    dnkn3[col] = pd.to_numeric(dnkn3[col])

In [63]:
print("========== MISSING VALUES ==========")
print(dnkn3.isnull().sum())

print("\n========== DATA TYPES ==========")
print(dnkn3.dtypes)

print("\n========== DUPLICATE RECORDS ==========")
print("Duplicates:", dnkn3.duplicated().sum())

print("\n========== CATEGORY CHECK ==========")
print(dnkn3['Category'].value_counts())

print("\n========== SPECIAL VALUE CHECK ==========")
print("Cholesterol Values:")
print(dnkn3['Cholesterol (mg)'].unique())

print("\nTotal Fat Values:")
print(dnkn3['Total Fat (g)'].unique())

print("\n========== DATASET SHAPE ==========")
print(dnkn3.shape)

print("\n========== SUMMARY STATISTICS ==========")
print(dnkn3.describe().round(2))

========== MISSING VALUES ==========
Category               0
Item                   0
Calories               0
Total Fat (g)          0
Saturated Fat (g)      0
Trans Fat (g)          0
Cholesterol (mg)       0
Sodium (mg)            0
Carbs (g)              0
Fiber (g)              0
Sugars (g)             0
Protein (g)            0
Weight Watcher Pnts    0
dtype: int64

========== DATA TYPES ==========
Category                   str
Item                       str
Calories                 int64
Total Fat (g)          float64
Saturated Fat (g)      float64
Trans Fat (g)          float64
Cholesterol (mg)         int64
Sodium (mg)              int64
Carbs (g)                int64
Fiber (g)                int64
Sugars (g)               int64
Protein (g)              int64
Weight Watcher Pnts    float64
dtype: object

========== DUPLICATE RECORDS ==========
Duplicates: 0

========== CATEGORY CHECK ==========
Category
Hot Coffee            88
Hot Latte             63
Iced Coffee           63
Iced Latte            63
Frozen Coffee         47
Hot Macchiato         45
Hot Cappuccino        42
Iced Cappuccino       42
Iced Macchiato        42
Iced Tea              33
Hot Chocolate         28
Cold Brew Coffee      11
Coolatta               9
Dunkin’ Refreshers     9
Soft Serve             8
Hot Americano          3
Iced Americano         3
Dunkin’ Bowls          1
Name: count, dtype: int64

========== SPECIAL VALUE CHECK ==========
Cholesterol Values:
[  0  35  25  20  15  10 130 100  70  40  30 105  80  55   5 125  50  45
  60]

Total Fat Values:
[ 0.  12.   9.   6.   4.5  3.  40.  31.  22.   5.  11.   8.  35.  26.
 17.  13.  14.  10.   7.   4.   1.   0.5 23.  21.  15.  16.   1.5  2.5
  2.  18.   3.5 20.  19.  27. ]

========== DATASET SHAPE ==========
(600, 13)

========== SUMMARY STATISTICS ==========
       Calories  Total Fat (g)  Saturated Fat (g)  Trans Fat (g)  \
count    600.00         600.00             600.00         600.00
mean     253.32           5.05               3.04           0.03
std      183.27           6.37               3.98           0.16
min        5.00           0.00               0.00           0.00
25%      130.00           0.00               0.00           0.00
50%      230.00           4.00               2.50           0.00
75%      340.00           8.00               4.50           0.00
max     1160.00          40.00              22.00           1.50

       Cholesterol (mg)  Sodium (mg)  Carbs (g)  Fiber (g)  Sugars (g)  \
count            600.00       600.00     600.00     600.00      600.00
mean              15.39       140.01      45.98       0.34       42.72
std               18.43       112.21      35.12       0.74       33.02
min                0.00         5.00       0.00       0.00        0.00
25%                0.00        60.00      25.00       0.00       23.00
50%               10.00       120.00      40.00       0.00       38.00
75%               25.00       190.00      63.00       0.00       57.00
max              130.00       750.00     195.00       4.00      185.00

       Protein (g)  Weight Watcher Pnts
count       600.00               600.00
mean          6.01               293.08
std           4.18               215.37
min           0.00                 4.00
25%           2.00               156.75
50%           6.00               265.75
75%           9.00               386.00
max          19.00              1352.00

In [64]:
dnkn3.to_csv(
    'dnkn_clean.csv',
    index=False
)

In [65]:
dnkn4 = pd.read_csv(
    'dnkn_clean.csv'
)
dnkn4.head()

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
0,Cold Brew Coffee,"Cold Brew Coffee, Large",5,0.0,0.0,0.0,0,20,0,0,0,1,4.0
1,Cold Brew Coffee,"Cold Brew Coffee, Medium",5,0.0,0.0,0.0,0,15,0,0,0,0,5.0
2,Cold Brew Coffee,"Cold Brew Coffee, Small",5,0.0,0.0,0.0,0,10,0,0,0,0,5.0
3,Cold Brew Coffee,"Cold Brew Coffee with Cream, Large",120,12.0,6.0,0.0,35,65,2,0,2,2,126.0
4,Cold Brew Coffee,"Cold Brew Coffee with Cream, Medium",90,9.0,4.5,0.0,25,45,1,0,1,2,93.5

In [ ]:
For Deliverable Two, I focused on cleaning and organizing the Dunkin dataset to make it more accurate and easier to analyze. I removed unnecessary spaces, unwanted characters, and converted colums into correct data types. All information was checked, verified, and cleaned in order to be ready for further analysis. Though these changes may seem insignifcant, they can cause problems when analyzing information, so by removing them I made the data easier to work with and anaylze.